In [1]:
##EJERCICIO 1
def generarMatriz(dimension):
    a=matrix(ZZ,dimension,dimension,lambda i,j:2 if i==j else -1)
    return a

show(generarMatriz(3))

[ 2 -1 -1]
[-1  2 -1]
[-1 -1  2]

In [3]:
##EJERCICIO 2
def aproximarError(error):
    contador=0
    n=1
    valorFuncion=0
    ejecutar=True
    while(ejecutar):
        valorFuncion=1/(n+1)
        contador+=1
        if(valorFuncion<=error):
            ejecutar=False
        n+=1
    return contador

show(aproximarError(0.05))


19

In [4]:
##EJERCICIO3
def comparacion(n):
    acumulador=1
    for i in(1..n):
        acumulador*=(4*i^2)/(4*i^2-1)
    return acumulador
print("Resultado función", float(comparacion(100)))
print("Resultado pi",float(pi/2))
       
    
    

Resultado función 1.5668937453140812
Resultado pi 1.5707963267948966


In [8]:
##EJERCICIO 4
def multiplicacionRusa(a, b):
    resultadosA = []
    resultadosB = []
    sumandos = []
    b_actual = b
    while a >= 1:
        resultadosA.append(a)
        resultadosB.append(b_actual)
        if a % 2 != 0:
            sumandos.append(b_actual)
        else:
            sumandos.append(0)
        a = a // 2
        b_actual = b_actual * 2
    show(resultadosA)
    show(resultadosB)
    show(sumandos)
    return sum(sumandos)

print(multiplicacionRusa(27, 82))
    

[27, 13, 6, 3, 1]

[82, 164, 328, 656, 1312]

[82, 164, 0, 656, 1312]

2214


In [9]:
##EJERCICIO 5
def numerosPrimos(valor):
    lista_primos=[]
    for p in primes(valor):
        if (p-1)%3==0:
            lista_primos.append(p)
    return lista_primos
show(numerosPrimos(50))

[7, 13, 19, 31, 37, 43]

In [17]:
##EJERCICIO 6
def elementoMaximo(matriz):
    show(max(max(matriz)))
    show(max(matriz.list()))
    show(matriz.numpy().max())
elementoMaximo(matrix.hilbert(4,RDF).n(digits=2))
matrizAleatoria=random_matrix(RDF,1000)
elementoMaximo(matrizAleatoria)
%time max(max(matrizAleatoria))
%time max(matrizAleatoria.list())
%time matrizAleatoria.numpy().max()

1.0

1.0

np.float64(1.0)

0.9993915374642848

0.999998960013714

np.float64(0.999998960013714)

CPU times: user 137 ms, sys: 0 ns, total: 137 ms
Wall time: 137 ms
CPU times: user 120 ms, sys: 16.7 ms, total: 137 ms
Wall time: 137 ms
CPU times: user 1.2 ms, sys: 24 μs, total: 1.22 ms
Wall time: 1.22 ms


np.float64(0.999998960013714)

In [18]:
## EJERCICIO 7
puntos_intervalo = lambda a, b, n: [a + i * (b - a) / n for i in range(n + 1)]

resultado = puntos_intervalo(1, 3, 3)
print(resultado) 
    
    
    

[1, 5/3, 7/3, 3]


In [28]:
## EJERCICIO 8
# 1. Definimos el anillo de polinomios con la variable x
R.<x> = PolynomialRing(RDF)

# 2. Creamos los puntos de la tabla
puntos = [(0, 0), (0.1, 0.06), (0.4, 0.17), (0.5, 0.19), 
          (0.6, 0.21), (1.0, 0.26), (1.4, 0.29), (1.5, 0.29)]

# 3. Calculamos el polinomio de Lagrange usando el anillo R
P_lagrange = R.lagrange_polynomial(puntos)
P_spline=spline(puntos)

# 4. Mostramos el resultado
show(P_lagrange)

# Dibujamos su gráfica junto con los puntos originales
graf_lagrange = plot(P_lagrange, 0, 1.5, color='blue', legend_label='Lagrange',frame=True)

graf_spline = plot(P_spline, 0, 1.5, color='green', legend_label='Spline',frame=True)

show(graf_lagrange + graf_spline)


-2.34071484071484*x^7 + 11.670042920042917*x^6 - 22.384296259296256*x^5 + 20.534546472046472*x^4 - 8.84840603840604*x^3 + 1.065282402782403*x^2 + 0.5635453435453435*x